### ISSUE TITLE
Version issues

### ISSUE THREAD

**Issue by mbrouer** [inspectIT/inspectIT-dvdstore-example#3]
Your docker DVDstore example version does not match the version you use in the docker CMR image 

dvdstore_1 | [ERROR] Agent: 1.6.7.79
dvdstore_1 | [ERROR] CMR: 1.6.9.83

Using the compose:

```
cmr:
  image: inspectit/cmr
  ports:
   - "8182:8182"
dvdstore:
  image: inspectit/dvdstore
  links:
   - cmr
  ports:
   - "8080:8080"
  environment:
   - AGENT_NAME=dvdstore
gui:
  image: inspectit/inspectit
  environment:
   - DISPLAY
   - XAUTHORITY=/.Xauth
  net: "host"
  volumes:
   - ${XAUTHORITY}:/.Xauth

```
